"""Packaging regression tests for pdomain-ocr-simple-gui.

These assert invariants about how the project is *packaged*, not about the
running app.

Regression guard for the built frontend SPA: hatchling only ships files from
``src/pdomain_ocr_simple_gui/frontend/`` if that directory is explicitly
force-included via the ``artifacts`` field in
``[tool.hatch.build.targets.wheel]``. Because ``frontend/`` is gitignored
(generated by ``make frontend-build``), hatchling's default VCS-based include
logic silently omits it. The symptom at install time is a 503 response to
every GET request because the static files are absent.

This test builds a real wheel (or locates one in ``dist/``) and asserts that
``pdomain_ocr_simple_gui/frontend/index.html`` is present inside it.
"""

from __future__ import annotations

import subprocess
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_DIR = REPO_ROOT / "src" / "pdomain_ocr_simple_gui"
FRONTEND_SRC = PACKAGE_DIR / "frontend"


def _locate_or_build_wheel(tmp_path: Path) -> Path:
    """Return an existing dist/ wheel or build a fresh one into *tmp_path*."""
    # Prefer a pre-built wheel in dist/ (faster in local-dev; release.yml
    # already ran frontend-build + uv build before the test suite).
    existing = sorted((REPO_ROOT / "dist").glob("pdomain_ocr_simple_gui-*.whl"))
    if existing:
        return existing[-1]

    # Fall back to building a wheel. Use python -m build if available, then uv.
    result = subprocess.run(
        [sys.executable, "-m", "build", "--wheel", "--outdir", str(tmp_path)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        result = subprocess.run(
            ["uv", "build", "--wheel", "--out-dir", str(tmp_path)],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
    assert result.returncode == 0, f"wheel build failed:\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"

    wheels = list(tmp_path.glob("pdomain_ocr_simple_gui-*.whl"))
    assert wheels, f"no wheel produced in {tmp_path}"
    return wheels[-1]


def test_pyproject_artifacts_includes_frontend() -> None:
    """``pyproject.toml`` must declare an ``artifacts`` glob covering the frontend.

    This is a lightweight static check that catches a misconfiguration before
    a wheel build is attempted. If the artifacts entry is absent, hatchling
    will silently omit the gitignored frontend/ directory and users will see
    HTTP 503 on every page load after a ``uv tool install``.
    """
    pyproject = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert "artifacts" in pyproject, (
        "pyproject.toml [tool.hatch.build.targets.wheel] must declare "
        "`artifacts` so the gitignored frontend/ build output ships in the wheel. "
        "Without it every `uv tool install` produces a 503-only app."
    )
    assert "pdomain_ocr_simple_gui/frontend" in pyproject, (
        "pyproject.toml artifacts glob must cover "
        "src/pdomain_ocr_simple_gui/frontend/** so the built SPA ships."
    )


def test_frontend_index_shipped_in_wheel(tmp_path: Path) -> None:
    """Building a wheel must include ``pdomain_ocr_simple_gui/frontend/index.html``.

    The pyproject.toml ``artifacts`` field existing is necessary but not
    sufficient: a glob typo or wrong path still produces a wheel without the
    frontend. Build (or locate) a real wheel and verify the file is present.

    This test is skipped when the frontend has not been built yet (no
    ``src/pdomain_ocr_simple_gui/frontend/index.html``), because hatch cannot
    include files that do not exist on disk at build time.
    """
    index_html = FRONTEND_SRC / "index.html"
    if not index_html.exists():
        import pytest

        pytest.skip(
            "frontend/index.html not present -- run `make frontend-build` first. "
            "This test is skipped in pure-Python CI runs without a prior build step."
        )

    wheel_path = _locate_or_build_wheel(tmp_path)

    with zipfile.ZipFile(wheel_path) as zf:
        names = zf.namelist()

    frontend_files = [n for n in names if "/frontend/" in n]
    assert any(n.endswith("pdomain_ocr_simple_gui/frontend/index.html") for n in names), (
        "pdomain_ocr_simple_gui/frontend/index.html is missing from the built wheel. "
        "Users would see HTTP 503 on every page load after `uv tool install`. "
        f"Frontend files found in wheel: {frontend_files!r}. "
        f"Full wheel: {sorted(names)}"
    )
    assert frontend_files, (
        "No files under pdomain_ocr_simple_gui/frontend/ found in the wheel. "
        "Check the `artifacts` glob in pyproject.toml."
    )
