"""Packaging regression tests for pdomain-ocr-simple-gui.

These assert invariants about how the project is *packaged*, not about the
running app.

Regression guard for the built frontend SPA: hatchling only ships files from
``src/pdomain_ocr_simple_gui/frontend/`` if that directory is explicitly
included via the ``artifacts`` field in both the global ``[tool.hatch.build]``
section (or per-target) and (belt-and-suspenders) via
``[tool.hatch.build.targets.wheel.force-include]``.

Because ``frontend/`` is gitignored (generated by ``make frontend-build``),
hatchling's default VCS-based include logic silently omits it. The symptom at
install time is a 503 response to every GET request because the static files
are absent.

The RELEASE BUILD PATH:
  1. ``make build`` runs ``frontend-build`` (vite), then ``uv build --sdist``
     and ``uv build --wheel`` (both from the git source tree).
  2. By default ``uv build`` (without explicit flags) builds the sdist from
     source and then builds the wheel *from the sdist* in a temporary non-git
     directory. That pipeline is also tested here (``test_wheel_from_sdist_*``).

The failure mode of ``b8a2b5f`` (wheel-only ``artifacts``) was:
  - Local plain ``uv build`` produced 78 frontend files in wheel (passes locally)
  - CI published wheel had 0 frontend files (fails on release)

This file exercises both build paths to catch regressions early.
"""

from __future__ import annotations

import subprocess
import tarfile
import zipfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
PACKAGE_DIR = REPO_ROOT / "src" / "pdomain_ocr_simple_gui"
FRONTEND_SRC = PACKAGE_DIR / "frontend"

# Minimum number of frontend assets expected in a full build.
# A fresh ``make frontend-build`` produces 78 files (index.html +
# manifest.webmanifest + ~76 asset files). Use a conservative floor so the
# assertion does not break on minor font/chunk count changes, but large enough
# to catch a "zero files" or "one file only" regression.
MIN_FRONTEND_FILE_COUNT = 40


def _require_frontend(test_name: str) -> None:
    """Skip *test_name* when the frontend has not been built yet."""
    if not (FRONTEND_SRC / "index.html").exists():
        pytest.skip(
            f"{test_name}: frontend/index.html not present -- "
            "run `make frontend-build` first. "
            "This test is skipped in pure-Python CI runs without a prior build step."
        )


def _count_frontend_in_wheel(wheel_path: Path) -> tuple[int, bool]:
    """Return (frontend_file_count, has_index_html) for *wheel_path*."""
    with zipfile.ZipFile(wheel_path) as zf:
        names = zf.namelist()
    fe = [n for n in names if "/frontend/" in n]
    has_index = any(n.endswith("pdomain_ocr_simple_gui/frontend/index.html") for n in names)
    return len(fe), has_index


def _count_frontend_in_sdist(sdist_path: Path) -> tuple[int, bool]:
    """Return (frontend_file_count_in_src_subdir, has_index_html) for *sdist_path*.

    Only counts files under ``src/pdomain_ocr_simple_gui/frontend/`` (the built
    SPA), not under the vite source tree at ``frontend/``.
    """
    with tarfile.open(sdist_path) as tf:
        members = tf.getnames()
    fe = [m for m in members if "src/pdomain_ocr_simple_gui/frontend/" in m]
    has_index = any(m.endswith("src/pdomain_ocr_simple_gui/frontend/index.html") for m in members)
    return len(fe), has_index


# ---------------------------------------------------------------------------
# Static / config checks (always run, no frontend required)
# ---------------------------------------------------------------------------


def test_pyproject_artifacts_includes_frontend() -> None:
    """``pyproject.toml`` must declare an ``artifacts`` glob covering the frontend.

    This lightweight static check catches a misconfiguration before a wheel
    build is attempted. If the artifacts entry is absent, hatchling silently
    omits the gitignored frontend/ directory and users see HTTP 503 on every
    page load after ``uv tool install``.
    """
    pyproject = (REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8")
    assert "artifacts" in pyproject, (
        "pyproject.toml must declare `artifacts` (in [tool.hatch.build] or "
        "[tool.hatch.build.targets.wheel]) so the gitignored frontend/ build "
        "output ships in the wheel. Without it every `uv tool install` produces "
        "a 503-only app."
    )
    assert "pdomain_ocr_simple_gui/frontend" in pyproject, (
        "pyproject.toml artifacts glob must cover "
        "src/pdomain_ocr_simple_gui/frontend/** so the built SPA ships."
    )


def test_makefile_build_uses_explicit_sdist_and_wheel() -> None:
    """The ``build`` Makefile target must build sdist and wheel separately from source.

    ``uv build`` (default, without explicit flags) builds the wheel *from the
    sdist* in a temporary non-git directory. If the sdist or wheel configuration
    is incorrect the frontend is silently dropped. Building both artifacts
    explicitly from the source tree (``uv build --sdist`` then
    ``uv build --wheel``) eliminates this failure mode.
    """
    makefile = (REPO_ROOT / "Makefile").read_text(encoding="utf-8")
    assert "uv build --sdist" in makefile and "uv build --wheel" in makefile, (
        "Makefile `build` target must run `uv build --sdist` and `uv build --wheel` "
        "as separate explicit commands (not bare `uv build`). "
        "Bare `uv build` builds the wheel from the sdist in a temp non-git dir, "
        "which can silently drop the gitignored frontend/ even when `artifacts` is "
        "configured only in [tool.hatch.build.targets.wheel]."
    )


# ---------------------------------------------------------------------------
# Release-path artifact checks (require frontend to be built; marked slow)
# ---------------------------------------------------------------------------


@pytest.mark.slow
def test_wheel_from_source_contains_frontend(tmp_path: Path) -> None:
    """Building the wheel directly from the source tree must include the frontend.

    This mirrors ``uv build --wheel`` (wheel from source, not from sdist).
    """
    _require_frontend("test_wheel_from_source_contains_frontend")

    wheel_dir = tmp_path / "wheel-from-source"
    wheel_dir.mkdir()
    result = subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(wheel_dir)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, (
        f"uv build --wheel failed:\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )

    wheels = sorted(wheel_dir.glob("pdomain_ocr_simple_gui-*.whl"))
    assert wheels, f"no wheel produced in {wheel_dir}"
    count, has_index = _count_frontend_in_wheel(wheels[-1])

    assert has_index, (
        "pdomain_ocr_simple_gui/frontend/index.html is missing from the wheel "
        "built directly from source. "
        f"Frontend files found: {count}. "
        "Check the `artifacts` glob in pyproject.toml."
    )
    assert count >= MIN_FRONTEND_FILE_COUNT, (
        f"Only {count} frontend files in the wheel (expected >= {MIN_FRONTEND_FILE_COUNT}). "
        "The full SPA should contain index.html + manifest + assets. "
        "Check the `artifacts` glob in pyproject.toml."
    )


@pytest.mark.slow
def test_sdist_contains_built_frontend(tmp_path: Path) -> None:
    """The sdist must include the built frontend SPA under src/pdomain_ocr_simple_gui/frontend/.

    Without the frontend in the sdist, ``uv build`` (default) produces a wheel
    from an sdist that has no frontend files, causing HTTP 503 on install.
    """
    _require_frontend("test_sdist_contains_built_frontend")

    sdist_dir = tmp_path / "sdist"
    sdist_dir.mkdir()
    result = subprocess.run(
        ["uv", "build", "--sdist", "--out-dir", str(sdist_dir)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, (
        f"uv build --sdist failed:\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )

    sdists = sorted(sdist_dir.glob("pdomain_ocr_simple_gui-*.tar.gz"))
    assert sdists, f"no sdist produced in {sdist_dir}"
    count, has_index = _count_frontend_in_sdist(sdists[-1])

    assert has_index, (
        "src/pdomain_ocr_simple_gui/frontend/index.html is missing from the sdist. "
        f"Frontend files found: {count}. "
        "The sdist must include the built SPA so that wheel-from-sdist pipelines "
        "can include the frontend. Check [tool.hatch.build] artifacts in pyproject.toml."
    )
    assert count >= MIN_FRONTEND_FILE_COUNT, (
        f"Only {count} frontend files in the sdist (expected >= {MIN_FRONTEND_FILE_COUNT}). "
        "Check [tool.hatch.build] artifacts in pyproject.toml."
    )


@pytest.mark.slow
def test_wheel_from_sdist_contains_frontend(tmp_path: Path) -> None:
    """Building the wheel from an unpacked sdist (non-git dir) must include the frontend.

    This is the wheel-from-sdist path: extracts the sdist to a directory with
    no ``.git`` and builds the wheel from there. This faithfully reproduces what
    ``uv build`` (default) does internally, and what the CI runner would do if
    ``make build`` used bare ``uv build`` instead of explicit ``--sdist`` /
    ``--wheel`` flags.

    The historical failure mode (b8a2b5f): wheel-only ``artifacts`` passed
    locally but produced 0 frontend files on the CI release wheel.
    """
    _require_frontend("test_wheel_from_sdist_contains_frontend")

    # Step 1: Build the sdist.
    sdist_dir = tmp_path / "sdist"
    sdist_dir.mkdir()
    result = subprocess.run(
        ["uv", "build", "--sdist", "--out-dir", str(sdist_dir)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, f"sdist build failed:\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    sdists = sorted(sdist_dir.glob("pdomain_ocr_simple_gui-*.tar.gz"))
    assert sdists, f"no sdist produced in {sdist_dir}"

    # Step 2: Unpack the sdist into a fresh directory (no .git).
    unpack_dir = tmp_path / "sdist-unpacked"
    unpack_dir.mkdir()
    with tarfile.open(sdists[-1]) as tf:
        tf.extractall(unpack_dir, filter="data")

    unpacked = sorted(unpack_dir.iterdir())
    assert unpacked, f"sdist extracted nothing into {unpack_dir}"
    sdist_root = unpacked[0]
    assert not (sdist_root / ".git").exists(), (
        "Unpacked sdist must NOT have a .git directory -- this simulates the "
        "non-git environment used by the CI wheel-from-sdist pipeline."
    )

    # Step 3: Build the wheel from the unpacked sdist (non-git environment).
    wheel_dir = tmp_path / "wheel-from-sdist"
    wheel_dir.mkdir()
    result = subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(wheel_dir), str(sdist_root)],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, (
        f"wheel-from-sdist build failed:\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
    wheels = sorted(wheel_dir.glob("pdomain_ocr_simple_gui-*.whl"))
    assert wheels, f"no wheel produced in {wheel_dir}"
    count, has_index = _count_frontend_in_wheel(wheels[-1])

    assert has_index, (
        "pdomain_ocr_simple_gui/frontend/index.html is missing from the wheel "
        "built from the unpacked sdist (non-git directory). "
        "This is the historical CI release failure mode. "
        f"Frontend files found: {count}. "
        "Fix: add `artifacts` to [tool.hatch.build] (global) AND use "
        "`uv build --sdist` + `uv build --wheel` in the Makefile build target."
    )
    assert count >= MIN_FRONTEND_FILE_COUNT, (
        f"Only {count} frontend files in the wheel-from-sdist "
        f"(expected >= {MIN_FRONTEND_FILE_COUNT}). "
        "This is the historical CI release failure mode."
    )


@pytest.mark.slow
def test_full_release_build_both_artifacts(tmp_path: Path) -> None:
    """The release build must produce a complete wheel and sdist (both with frontend).

    Exercises the same sequence as the CI release workflow:
    1. frontend already built (``make frontend-build`` prerequisite)
    2. ``uv build --sdist`` then ``uv build --wheel`` from source

    Both artifacts must contain the full frontend.
    """
    _require_frontend("test_full_release_build_both_artifacts")

    out_dir = tmp_path / "release-out"
    out_dir.mkdir()

    # Build sdist and wheel from source (same as updated make build target).
    for flag in ("--sdist", "--wheel"):
        result = subprocess.run(
            ["uv", "build", flag, "--out-dir", str(out_dir)],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        assert result.returncode == 0, (
            f"uv build {flag} failed:\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )

    wheels = sorted(out_dir.glob("pdomain_ocr_simple_gui-*.whl"))
    sdists = sorted(out_dir.glob("pdomain_ocr_simple_gui-*.tar.gz"))
    assert len(wheels) == 1, f"expected exactly one wheel, got: {wheels}"
    assert len(sdists) == 1, f"expected exactly one sdist, got: {sdists}"

    whl_count, whl_has_index = _count_frontend_in_wheel(wheels[0])
    sdist_count, sdist_has_index = _count_frontend_in_sdist(sdists[0])

    assert whl_has_index, (
        "frontend/index.html missing from wheel. "
        f"Wheel frontend files: {whl_count}. "
        "Check `artifacts` in pyproject.toml."
    )
    assert whl_count >= MIN_FRONTEND_FILE_COUNT, (
        f"Wheel has only {whl_count} frontend files (expected >= {MIN_FRONTEND_FILE_COUNT})."
    )
    assert sdist_has_index, (
        "frontend/index.html missing from sdist under src/pdomain_ocr_simple_gui/frontend/. "
        f"Sdist frontend files: {sdist_count}. "
        "Check global `artifacts` in pyproject.toml."
    )
    assert sdist_count >= MIN_FRONTEND_FILE_COUNT, (
        f"Sdist has only {sdist_count} frontend files (expected >= {MIN_FRONTEND_FILE_COUNT})."
    )


# ---------------------------------------------------------------------------
# Backward-compat: the original wheel-only test (preserved, simplified)
# ---------------------------------------------------------------------------


def test_frontend_index_shipped_in_wheel(tmp_path: Path) -> None:
    """Building a wheel must include ``pdomain_ocr_simple_gui/frontend/index.html``.

    Original regression guard (preserved for backward compatibility).
    ``test_wheel_from_source_contains_frontend`` and
    ``test_wheel_from_sdist_contains_frontend`` provide more faithful
    reproductions of the release build path.

    This test is skipped when the frontend has not been built yet.
    """
    _require_frontend("test_frontend_index_shipped_in_wheel")

    wheel_dir = tmp_path / "wheel"
    wheel_dir.mkdir()
    result = subprocess.run(
        ["uv", "build", "--wheel", "--out-dir", str(wheel_dir)],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, f"wheel build failed:\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    wheels = sorted(wheel_dir.glob("pdomain_ocr_simple_gui-*.whl"))
    assert wheels, f"no wheel produced in {wheel_dir}"

    count, has_index = _count_frontend_in_wheel(wheels[-1])

    assert has_index, (
        "pdomain_ocr_simple_gui/frontend/index.html is missing from the built wheel. "
        "Users would see HTTP 503 on every page load after `uv tool install`. "
        f"Frontend files found in wheel: {count}."
    )
    assert count >= MIN_FRONTEND_FILE_COUNT, (
        f"Only {count} frontend files in wheel (expected >= {MIN_FRONTEND_FILE_COUNT}). "
        "Check the `artifacts` glob in pyproject.toml."
    )
